### PR TITLE
Run ci on PRs to release branches

### PR DESCRIPTION
**Pull request by tomkennedy513**

### CODE REVIEW

**Comment by chenbh** [comment]
Don't we already run the unit tests on PRs? Why do we need to full suite?

**Comment by chenbh** [comment]
Oh is the expectation that since PRs to release branches are always from this repo, they will always have the correct creds to run the full suite?

**Comment by tomkennedy513** [comment]
Ya I am trying to avoid ever having the release branch in a non releasable state

**Comment by tomkennedy513** [comment]
Only maintainers can make prs to release branches so it will always happen from the repo

**Review by samj1912 — APPROVED** [review]

**Pull request merged**
